general:
   debug_on: False
   logging_level: "WARNING" # switch to control logging - WARNING for full logging; ERROR to minimize logging
   BATCH_SIZE: 1000
scoring_columns_cat: # categorical columns
      - 'location'
      - 'size_type'
      - 'property_type'
      - 'furnishing'
scoring_columns_cont:
      - 'rooms'
      - 'bathrooms'
      - 'car_parks'
      - 'size'
file_names:
   saved_model: 'kl_real_estate_keras_preprocessing_model'